### ISSUE TITLE
compare tun2proxy via tun2socks

### ISSUE THREAD

**Issue by foxhacker0000** [blechschmidt/tun2proxy#39]
i tested both on linux and tun2proxy have more speed for me

do you use tun2socks api?
its very good

**Comment by blechschmidt** [comment]
Internally, tun2proxy makes use of the [smoltcp](https://github.com/smoltcp-rs/smoltcp) network stack. In my small manual tests, [tun2socks](https://github.com/xjasonlyu/tun2socks) was about 20% faster. I suspect the reason is that [smoltcp](https://github.com/smoltcp-rs/smoltcp) lacks congestion control.
