### ISSUE TITLE
Unsupported protocol 0x80 in IP packet

### ISSUE THREAD

**Issue by acheong08** [blechschmidt/tun2proxy#53]
```bash
# sudo tun2proxy -p "socks5://127.0.0.1:1090" -s auto --bypass-ip <server-ip>

[2023-08-13T04:47:38Z INFO  tun2proxy] Proxy socks5 server: 127.0.0.1:1090
[2023-08-13T04:47:38Z INFO  tun2proxy::setup] [11026] Setting up network configuration
[2023-08-13T04:47:38Z ERROR tun2proxy::tun2proxy] Unsupported protocol 0x80 in IP packet
^C[2023-08-13T04:47:39Z INFO  tun2proxy::setup] [11027] Restoring network configuration
```

**Comment by ssrlive** [comment]
So it's strange that 0x08 means.
![image](https://github.com/blechschmidt/tun2proxy/assets/30760636/4ad0901d-b755-4f2d-a5a4-95059a0ae22f)

**Comment by acheong08** [comment]
I tested this with a number of socks5 proxies (my own) which worked previously but all report the same error.

The servers have not changed.

The only difference I can think of is that I started using Fedora instead of Ubuntu. Shouldn't have an effect though

**Comment by ssrlive** [comment]
This is from my PC.
![image](https://github.com/blechschmidt/tun2proxy/assets/30760636/d8ad0445-716b-48ae-ba2f-2102b07d5756)
Don't mind it. The previous versions didn't report this error because tun2proxy silently ignored it. Now it's being printed out. That's the only difference. tun2proxy only handles TCP and UDP packets.

**Comment by acheong08** [comment]
Thanks. Seems like I was running an older version on my previous laptop
